### ISSUE TITLE
Language detection not working

### ISSUE THREAD

**Issue by thommck** [azure-labs/cognitive-services-function#1]
I've pulled this into an Azure Function app as part of the lab on the 70-533 course.
When I try to test the Language Detection I get an Internal Server 500 error.
You can reproduce the issue by following the steps https://microsoftlearning.github.io/20535-ArchitectingMicrosoftAzureSolutions/Instructions/Labs/Mod10/20535A_LAB_AK_10.html

**Comment by surlypants** [comment]
confirmed during 70-535 course.

**Comment by seesharprun** [comment]
I have someone who is working on fixing this bug this week. The new version of Azure Functions requires you to use ILogger for logging instead of the old-school TraceWriter class. It's a simple fix.

**Comment by seesharprun** [comment]
I authored two commits to solve the code issue in this repository. Changes include:

- Using the new ``IActionResult`` return value
- Using the new ``HttpRequest`` parameter
- Returning values using the ``OkObjectResult`` class
- Updating the way application settings are read

I will now create an issue in the 20535 repository to make sure this is fixed there too.

**Comment by thommck** [comment]
That's working great now, thanks 👍
